server:
  port: 9000
  netty:
    connection-timeout: 5s
  shutdown: graceful
spring:
  cloud:
    gateway:
      routes:
        - id: catalog-route
          uri: ${CATALOG_SERVICE_URL:http://localhost:9002}/books
          predicates:
            - Path=/books/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogCircuitBreaker
                fallbackUri: forward:/catalog-fallback
        - id: order_service
          uri: ${ORDER_SERVICE_URL:http://localhost:9003}/orders
          predicates:
            - Path=/orders/**
          filters:
            - name: CircuitBreaker
              args:
                name: orderCircuitBreaker
logging:
  level:
    io.github.resilience4j: DEBUG
